### PR TITLE
Ci/travis ci

### PR DESCRIPTION
**Pull request by iforgotband**

### CODE REVIEW

**Comment by ximion** [comment]
This will not work. This code will only build in a PureOS environment with a bunch of libraries installed, it also doesn't make much sense to add any CI here since the real changes are happening on the PureOS packages and we are already building new images regularly on our infrastructure.

**Comment by ximion** [comment]
Additionally, in case you want to make a new image, debootstrap a PureOS environment, install live-build and run the build via `lb config && lb build` - the scripts are not supposed to be executed directly.

**Comment by iforgotband** [comment]
No kidding. Adjust the script to use your own repo. I'm sorry but I was giving you the respect of assuming you'd pick up on that ;).

I'll withdraw the pr, and withhold any future contributions. Bye now.

**Comment by iforgotband** [comment]
Okay again you're not apparently too bright here ... Then again Todd hired you, so ... well I mean look at the guy's history. Anyway that's not the point.

I give no shits about PureOS at all. I saw a script that was very poorly constructed, and decided to chip in. Take it or leave it, but shut up.

**Comment by iforgotband** [comment]
Here's what you all need to understand ... You don't understand the meaning of "Continuous Integration."

Get DevOps. This is embarrassing.

**Pull request closed without merging**
